type KeywordDef = {
  reserved?: boolean;
  requiresAs?: boolean;
  cannotBeFunctionOrType?: boolean;
  canBeFunctionOrType?: boolean;
};

// https://www.postgresql.org/docs/16/sql-keywords-appendix.html
const keywordDefs: Record<string, KeywordDef> = {
  ALL: { reserved: true },
  ANALYSE: { reserved: true },
  ANALYZE: { reserved: true },
  AND: { reserved: true },
  ANY: { reserved: true },
  ARRAY: { reserved: true, requiresAs: true },
  AS: { reserved: true, requiresAs: true },
  ASC: { reserved: true },
  ASYMMETRIC: { reserved: true },
  AUTHORIZATION: { reserved: true, canBeFunctionOrType: true },
  BETWEEN: { cannotBeFunctionOrType: true },
  BIGINT: { cannotBeFunctionOrType: true },
  BINARY: { reserved: true, canBeFunctionOrType: true },
  BIT: { cannotBeFunctionOrType: true },
  BOOLEAN: { cannotBeFunctionOrType: true },
  BOTH: { reserved: true },
  CASE: { reserved: true },
  CAST: { reserved: true },
  CHAR: { cannotBeFunctionOrType: true, requiresAs: true },
  CHARACTER: { cannotBeFunctionOrType: true, requiresAs: true },
  CHECK: { reserved: true },
  COALESCE: { cannotBeFunctionOrType: true },
  COLLATE: { reserved: true },
  COLLATION: { reserved: true, canBeFunctionOrType: true },
  COLUMN: { reserved: true },
  CONCURRENTLY: { reserved: true, canBeFunctionOrType: true },
  CONSTRAINT: { reserved: true },
  CREATE: { reserved: true, requiresAs: true },
  CROSS: { reserved: true, canBeFunctionOrType: true },
  CURRENT_CATALOG: { reserved: true },
  CURRENT_DATE: { reserved: true },
  CURRENT_ROLE: { reserved: true },
  CURRENT_SCHEMA: { reserved: true, canBeFunctionOrType: true },
  CURRENT_TIME: { reserved: true },
  CURRENT_TIMESTAMP: { reserved: true },
  CURRENT_USER: { reserved: true },
  DAY: { requiresAs: true },
  DEC: { cannotBeFunctionOrType: true },
  DECIMAL: { cannotBeFunctionOrType: true },
  DEFAULT: { reserved: true },
  DEFERRABLE: { reserved: true },
  DESC: { reserved: true },
  DISTINCT: { reserved: true },
  DO: { reserved: true },
  ELSE: { reserved: true },
  END: { reserved: true },
  EXCEPT: { reserved: true, requiresAs: true },
  EXISTS: { cannotBeFunctionOrType: true },
  EXTRACT: { cannotBeFunctionOrType: true },
  FALSE: { reserved: true },
  FETCH: { reserved: true, requiresAs: true },
  FILTER: { requiresAs: true },
  FLOAT: { cannotBeFunctionOrType: true },
  FOR: { reserved: true, requiresAs: true },
  FOREIGN: { reserved: true },
  FREEZE: { reserved: true, canBeFunctionOrType: true },
  FROM: { reserved: true, requiresAs: true },
  FULL: { reserved: true, canBeFunctionOrType: true },
  GRANT: { reserved: true, requiresAs: true },
  GREATEST: { cannotBeFunctionOrType: true },
  GROUP: { reserved: true, requiresAs: true },
  GROUPING: { cannotBeFunctionOrType: true },
  HAVING: { reserved: true, requiresAs: true },
  HOUR: { requiresAs: true },
  ILIKE: { reserved: true, canBeFunctionOrType: true },
  IN: { reserved: true },
  INITIALLY: { reserved: true },
  INNER: { reserved: true, canBeFunctionOrType: true },
  INOUT: { cannotBeFunctionOrType: true },
  INT: { cannotBeFunctionOrType: true },
  INTEGER: { cannotBeFunctionOrType: true },
  INTERSECT: { reserved: true, requiresAs: true },
  INTERVAL: { cannotBeFunctionOrType: true },
  INTO: { reserved: true, requiresAs: true },
  IS: { reserved: true, canBeFunctionOrType: true },
  ISNULL: { reserved: true, canBeFunctionOrType: true, requiresAs: true },
  JOIN: { reserved: true, canBeFunctionOrType: true },
  LATERAL: { reserved: true },
  LEADING: { reserved: true },
  LEAST: { cannotBeFunctionOrType: true },
  LEFT: { reserved: true, canBeFunctionOrType: true },
  LIKE: { reserved: true, canBeFunctionOrType: true },
  LIMIT: { reserved: true, requiresAs: true },
  LOCALTIME: { reserved: true },
  LOCALTIMESTAMP: { reserved: true },
  MINUTE: { requiresAs: true },
  MONTH: { requiresAs: true },
  NATIONAL: { cannotBeFunctionOrType: true },
  NATURAL: { reserved: true, canBeFunctionOrType: true },
  NCHAR: { cannotBeFunctionOrType: true },
  NONE: { cannotBeFunctionOrType: true },
  NORMALIZE: { cannotBeFunctionOrType: true },
  NOT: { reserved: true },
  NOTNULL: { reserved: true, canBeFunctionOrType: true, requiresAs: true },
  NULL: { reserved: true },
  NULLIF: { cannotBeFunctionOrType: true },
  NUMERIC: { cannotBeFunctionOrType: true },
  OFFSET: { reserved: true, requiresAs: true },
  ON: { reserved: true, requiresAs: true },
  ONLY: { reserved: true },
  OR: { reserved: true },
  ORDER: { reserved: true, requiresAs: true },
  OUT: { cannotBeFunctionOrType: true },
  OUTER: { reserved: true, canBeFunctionOrType: true },
  OVER: { requiresAs: true },
  OVERLAPS: { reserved: true, canBeFunctionOrType: true, requiresAs: true },
  OVERLAY: { cannotBeFunctionOrType: true },
  PLACING: { reserved: true },
  POSITION: { cannotBeFunctionOrType: true },
  PRECISION: { cannotBeFunctionOrType: true, requiresAs: true },
  PRIMARY: { reserved: true },
  REAL: { cannotBeFunctionOrType: true },
  REFERENCES: { reserved: true },
  RETURNING: { reserved: true, requiresAs: true },
  RIGHT: { reserved: true, canBeFunctionOrType: true },
  ROW: { cannotBeFunctionOrType: true },
  SECOND: { requiresAs: true },
  SELECT: { reserved: true },
  SESSION_USER: { reserved: true },
  SETOF: { cannotBeFunctionOrType: true },
  SIMILAR: { reserved: true, canBeFunctionOrType: true },
  SMALLINT: { cannotBeFunctionOrType: true },
  SOME: { reserved: true },
  SUBSTRING: { cannotBeFunctionOrType: true },
  SYMMETRIC: { reserved: true },
  SYSTEM_USER: { reserved: true },
  TABLE: { reserved: true },
  TABLESAMPLE: { reserved: true, canBeFunctionOrType: true },
  THEN: { reserved: true },
  TIME: { cannotBeFunctionOrType: true },
  TIMESTAMP: { cannotBeFunctionOrType: true },
  TO: { reserved: true, requiresAs: true },
  TRAILING: { reserved: true },
  TREAT: { cannotBeFunctionOrType: true },
  TRIM: { cannotBeFunctionOrType: true },
  TRUE: { reserved: true },
  UNION: { reserved: true, requiresAs: true },
  UNIQUE: { reserved: true },
  USER: { reserved: true },
  USING: { reserved: true },
  VALUES: { cannotBeFunctionOrType: true },
  VARCHAR: { cannotBeFunctionOrType: true },
  VARIADIC: { reserved: true },
  VARYING: { requiresAs: true },
  VERBOSE: { reserved: true, canBeFunctionOrType: true },
  WHEN: { reserved: true },
  WHERE: { reserved: true, requiresAs: true },
  WINDOW: { reserved: true, requiresAs: true },
  WITH: { reserved: true, requiresAs: true },
  WITHIN: { requiresAs: true },
  WITHOUT: { requiresAs: true },
  XMLATTRIBUTES: { cannotBeFunctionOrType: true },
  XMLCONCAT: { cannotBeFunctionOrType: true },
  XMLELEMENT: { cannotBeFunctionOrType: true },
  XMLEXISTS: { cannotBeFunctionOrType: true },
  XMLFOREST: { cannotBeFunctionOrType: true },
  XMLNAMESPACES: { cannotBeFunctionOrType: true },
  XMLPARSE: { cannotBeFunctionOrType: true },
  XMLPI: { cannotBeFunctionOrType: true },
  XMLROOT: { cannotBeFunctionOrType: true },
  XMLSERIALIZE: { cannotBeFunctionOrType: true },
  XMLTABLE: { cannotBeFunctionOrType: true },
  YEAR: { requiresAs: true },
};

export const postgresqlKeywords: Record<string, boolean> = {
  ...Object.fromEntries(
    Object.entries(keywordDefs)
      .filter(([_, def]) => def.reserved)
      .map(([kw]) => [kw, true])
  ),
};

export const postgresqlRequiresAsKeywords: Record<string, boolean> = {
  ...Object.fromEntries(
    Object.entries(keywordDefs)
      .filter(([_, def]) => def.requiresAs || def.reserved)
      .map(([kw]) => [kw, true])
  ),

  // TODO: SET is non-reserved keyword in PostgreSQL
  // and it's also allowed as implicit alias,
  // but that causes a "conflict" in UPDATE ... SET statement.
  //
  // The following is allowed:
  // UPDATE foo SET set = 10;
  //
  // But the following is error:
  // UPDATE foo set SET x = 10;
  //
  // PostgreSQL parser pulls some magic to deal with this.
  // As only crazy people really need this, and most other dialects treat SET
  // as reserved keyword, we'll require AS for SET as a workaround for now.
  SET: true,
};
