// SQLite keywords are listed in:
// https://www.sqlite.org/lang_keywords.html
//
// However, not all of them are fully reserved.
// I've marked the ones that by my testing are reserved with (R).
// This might or might not be fully accurate.
//
// Some keywords are never reserved. I've removed these from the list:
// - KEY
// Some are reserved only in certain contexts. I've removed these from the list:
// - COLUMN
//
// The following map lists the contexts in which the keywords are reserved.
// If the array is empty, then the keyword is reserved in all contexts.
//
// The contexts are:
// - "create table": cannot be used in: CREATE TABLE <kw> (id INT)
//
export const keywordDefs: Record<string, string[]> = {
  ABORT: [],
  ACTION: [],
  ADD: ["create table"],
  AFTER: [],
  ALL: ["create table"],
  ALTER: ["create table"],
  ALWAYS: [],
  ANALYZE: [],
  AND: ["create table"],
  AS: ["create table"],
  ASC: [],
  ATTACH: [],
  AUTOINCREMENT: ["create table"],
  BEFORE: [],
  BEGIN: [],
  BETWEEN: [],
  BY: [],
  CASCADE: [],
  CASE: [],
  CAST: [],
  CHECK: [],
  COLLATE: [],
  COMMIT: [],
  CONFLICT: [],
  CONSTRAINT: [],
  CREATE: [],
  CROSS: [],
  CURRENT: [],
  CURRENT_DATE: [],
  CURRENT_TIME: [],
  CURRENT_TIMESTAMP: [],
  DATABASE: [],
  DEFAULT: [],
  DEFERRABLE: [],
  DEFERRED: [],
  DELETE: [],
  DESC: [],
  DETACH: [],
  DISTINCT: ["create table"],
  DO: [],
  DROP: ["create table"],
  EACH: [],
  ELSE: ["create table"],
  END: [],
  ESCAPE: ["create table"],
  EXCEPT: ["create table"],
  EXCLUDE: [],
  EXCLUSIVE: [],
  EXISTS: ["create table"],
  EXPLAIN: [],
  FAIL: [],
  FILTER: [],
  FIRST: [],
  FOLLOWING: [],
  FOR: [],
  FOREIGN: ["create table"],
  FROM: ["create table"],
  FULL: [],
  GENERATED: [],
  GLOB: [],
  GROUP: ["create table"],
  GROUPS: [],
  HAVING: ["create table"],
  IF: ["create table"],
  IGNORE: [],
  IMMEDIATE: [],
  IN: ["create table"],
  INDEX: ["create table"],
  INDEXED: [],
  INITIALLY: [],
  INNER: [],
  INSERT: ["create table"],
  INSTEAD: [],
  INTERSECT: ["create table"],
  INTO: ["create table"],
  IS: ["create table"],
  ISNULL: ["create table"],
  JOIN: ["create table"],
  LAST: [],
  LEFT: [],
  LIKE: [],
  LIMIT: ["create table"],
  MATCH: [],
  MATERIALIZED: [],
  NATURAL: [],
  NO: [],
  NOT: ["create table"],
  NOTHING: ["create table"],
  NOTNULL: ["create table"],
  NULL: ["create table"],
  NULLS: [],
  OF: [],
  OFFSET: [],
  ON: ["create table"],
  OR: ["create table"],
  ORDER: ["create table"],
  OTHERS: [],
  OUTER: [],
  OVER: [],
  PARTITION: [],
  PLAN: [],
  PRAGMA: [],
  PRECEDING: [],
  PRIMARY: ["create table"],
  QUERY: [],
  RAISE: [],
  RANGE: [],
  RECURSIVE: [],
  REFERENCES: ["create table"],
  REGEXP: [],
  REINDEX: [],
  RELEASE: [],
  RENAME: [],
  REPLACE: [],
  RESTRICT: [],
  RETURNING: ["create table"],
  RIGHT: [],
  ROLLBACK: [],
  ROW: [],
  ROWS: [],
  SAVEPOINT: [],
  SELECT: ["create table"],
  SET: ["create table"],
  TABLE: ["create table"],
  TEMP: [],
  TEMPORARY: [],
  THEN: ["create table"],
  TIES: [],
  TO: ["create table"],
  TRANSACTION: ["create table"],
  TRIGGER: [],
  UNBOUNDED: [],
  UNION: ["create table"],
  UNIQUE: ["create table"],
  UPDATE: ["create table"],
  USING: ["create table"],
  VACUUM: [],
  VALUES: ["create table"],
  VIEW: [],
  VIRTUAL: [],
  WHEN: ["create table"],
  WHERE: ["create table"],
  WINDOW: [],
  WITH: [],
  WITHOUT: [],
};

export const sqliteKeywords: Record<string, boolean> = Object.fromEntries(
  Object.keys(keywordDefs).map((k) => [k, true])
);
